[color]
;; Main Colors (Dracula/Keyitdev Palette)
background = #1b1b25
foreground = #dedede
transparent = #00000000

;; Accent Colors
black = #15121c
red = #cb5760
green = #999f63
yellow = #d4a067
blue = #6c90a8
purple = #776690
cyan = #528a9b
white = #eeffff
orange = #c87c3e
gray = #727480

;; Special
primary = #776690
secondary = #528a9b
alert = #cb5760
